version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">= 19"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
